// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlxkdcqejjhzluhuinun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhseGtkY3Flampoemx1aHVpbnVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTY3NDksImV4cCI6MjA3MjY3Mjc0OX0.iTYXxynXDyoQ-WFre2S4hBpAT74cM9d95gQhzob_RNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});